---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c26,c0
    openshift.io/sa.scc.supplemental-groups: 1000650000/10000
    openshift.io/sa.scc.uid-range: 1000650000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2025-11-17T09:23:49Z"
  labels:
    kubernetes.io/metadata.name: openshift-ingress-canary
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: Go-http-client
    operation: Update
    time: "2025-11-17T09:23:49Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2025-11-17T09:23:49Z"
  name: openshift-ingress-canary
  resourceVersion: "12951"
  uid: c272bff9-d5ad-48f6-bc33-04cd556394f3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
