---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2025-11-17T09:06:18Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:06:18Z"
  name: prometheus-k8s-cluster-baremetal-operator
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "2480"
  uid: c557413d-3a09-4bed-9515-24f30181392d
rules:
- apiGroups:
  - ""
  resources:
  - namespace/metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
