---
apiVersion: v1
items:
- apiVersion: v1
  data:
    ca-bundle.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDOTCCAiGgAwIBAgIIQrt6djMgGBQwDQYJKoZIhvcNAQELBQAwKjESMBAGA1UE
      CxMJb3BlbnNoaWZ0MRQwEgYDVQQDEwtldGNkLXNpZ25lcjAeFw0yNTExMTcwOTAz
      MjFaFw0zNTExMTUwOTAzMjJaMCoxEjAQBgNVBAsTCW9wZW5zaGlmdDEUMBIGA1UE
      AxMLZXRjZC1zaWduZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJ
      e2gWigytw+/eFYtCucTF4/gsYMct8B3tZ+GZU2/IoUR2Du/CQv/y/cE+va7H5m10
      eeEiNHITNQGJ2AQK6FKZPnZ8CY4ghrPRo49NzUjvyw2M7pewYa+v73o9DV/rlqcL
      PAUhYyl4s45YfgDgpKa/lluvOztXyUrd/HmJ+9jbJ+RULYJULFkkhiNQLFTZkruk
      AGCRgDvDvrurHtZAZ3Ldc2qHpdiLXdl2CuXINNopa0pjcM0zcdtpxL7SFvGp3TeX
      1vF3f7ikseDOYDpFepZ0X6Dv+0bW+I5s5gVqxiR1/73Hc4KL8GpKjDoy95WE44Sq
      /bWLRl/nd0no4MWmkbSzAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMB
      Af8EBTADAQH/MB0GA1UdDgQWBBRA7ClH//Iksr3Ik7s2AwMSmiZnvjAfBgNVHSME
      GDAWgBRA7ClH//Iksr3Ik7s2AwMSmiZnvjANBgkqhkiG9w0BAQsFAAOCAQEAb1My
      QTOiozhnLL4700jU8L7TsHSQ/nlQIZpV45vDQ12sqDBsZXHH23okWDWHjQT55Q+s
      D/Z24h3pl1NiIsqERNlO1/b6sNMjQGAbdW1zrsTvbPB7H6X+hGxfTnco3Lt2C6j2
      kn/45qqyypYA/h0gVP5CHRjOzOouh7LGR+IyA56tE2f7hMfvM2fk0LfzaexGP3oJ
      PeTIMTLKXw0irMj9ALL4TWf4DvmN4jVMS3/B3Ce2kEp2Iuqz2dWUlGSIxXG+u1t+
      P1d7AXUl/M9Yt6SSp9uiGveOgwCeeU82CQl3CuhdCcORbYy+9/ccjOQs5lhRgYHs
      c6B0h7nOAYoFSsEF4A==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2025-11-17T09:05:33Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:33Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca-bundle.crt: {}
      manager: cluster-etcd-operator
      operation: Update
      time: "2025-11-17T09:20:24Z"
    name: etcd-ca-bundle
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "6739"
    uid: d407bac5-58cc-415d-884d-56f22cef458b
- apiVersion: v1
  data:
    ca-bundle.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDRzCCAi+gAwIBAgIILKud8fotQp4wDQYJKoZIhvcNAQELBQAwMTESMBAGA1UE
      CxMJb3BlbnNoaWZ0MRswGQYDVQQDExJldGNkLW1ldHJpYy1zaWduZXIwHhcNMjUx
      MTE3MDkwMzIyWhcNMzUxMTE1MDkwMzIzWjAxMRIwEAYDVQQLEwlvcGVuc2hpZnQx
      GzAZBgNVBAMTEmV0Y2QtbWV0cmljLXNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBAKnrzDrdAEjewKGyr6yV/O370IbpmuPO9jbCn3zatSmOknK0
      W6Yqg5CKFoNucG448z+LSrBmk9KRXgDIc0VWyTGz062OyaMyK5O8zH2CvwU5Agxr
      18EU6vAeNyK/orP8vJQajhkhSj1pqRxLsBRG8d8JqSvEE+ed4pD5mTPCG63UnlbM
      01RKBqNu+4ngrfzPcXDsWrma5hqYjcDKr3Fr9BW4723MrcxMcUnlHGxeIjlXeHK6
      JmnEacDziVWj+VVBfY3Fe65/0rvKLIjJmtdn0X/xLIZdeGRcYUmoeq34aR+QxG3w
      nMoYL/LhKuLjnqeEYerEUnp+ve2MC2P6mDOuPjUCAwEAAaNjMGEwDgYDVR0PAQH/
      BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGkRmCwhldvguEMfXjf+
      W+UHmhnUMB8GA1UdIwQYMBaAFGkRmCwhldvguEMfXjf+W+UHmhnUMA0GCSqGSIb3
      DQEBCwUAA4IBAQA9wksjyiXJr8CVnOaDHF5UER6VrRd17RlNyNc6K15mohxIyamW
      T/XnBwTAxQ1KCJtpVtUQF0bMoVpdWVSEQDYrjPB+1Gtc0aulqGxDFSw5ZIIgZs3Z
      jyU5JfevTKE2Fs6h5IYn+Q8Up4d/mwxnCNA57x6KmYCa9fA0hbkTqasA0jVAbwcK
      ajzX5wvNqq0gzLjqGEbhJ4KC2q2oF4yur2XvYk8QlkVNyMlKbfzwdRasCxo2Pfa6
      QbM/p80wpAjbML7DAOC5HEMeEtdQfqtHYT1SJRtkV6kDB0I+MytGYRAV4mBiI6PQ
      /2ndbPZdmYpm+J/oqz6nSp7FtgaZKbu+plw9
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-11-17T09:20:23Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca-bundle.crt: {}
      manager: cluster-etcd-operator
      operation: Update
      time: "2025-11-17T09:20:23Z"
    name: etcd-metric-serving-ca
    namespace: openshift-etcd-operator
    resourceVersion: "6604"
    uid: 11c88c1b-5230-4ec2-8cad-19ce34069185
- apiVersion: v1
  data:
    config.yaml: |
      apiVersion: operator.openshift.io/v1alpha1
      kind: GenericOperatorConfig
  kind: ConfigMap
  metadata:
    annotations:
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
    creationTimestamp: "2025-11-17T09:05:32Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:config.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:32Z"
    name: etcd-operator-config
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "1167"
    uid: ffa18af4-500c-4fae-8772-c00fb7ea6745
- apiVersion: v1
  data:
    service-ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIIHKUjOpzJvOowDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
      Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc2MzM3MTIyMDAe
      Fw0yNTExMTcwOTIwMTlaFw0yODAxMTYwOTIwMjBaMDYxNDAyBgNVBAMMK29wZW5z
      aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NjMzNzEyMjAwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJZslGqtAyG+AF1bCbVlUs9sQRLkmJ7l6v
      lUzDwf7FOFhJEqdN7VkIx0nX/mxYUYV1jGURo06noKZrWV6z4LXOfcw4X4XIOzkx
      YNm1kyD9MJGyx6Uv9ZxiAsguqqGwBt0Sf8fXbcqSBCcty7Myr0BNsB/K3FJvbE8p
      nTx+1G+PrmBkRES8GJe7Av7S31gnvZl2J6V7EkyIBJtSHt57Zcs9FBmuDQcphPhg
      38jgQhzlLpUbLMkcJLAD9/polbrprn4prszIlJeew5AqkVsBKffJzeikRgtxU97L
      VkmInVytBlB7mp7rjuIl3mB7oimj5UfVwdT5FG+KwDiaoboG41Q9AgMBAAGjYzBh
      MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQXa9VP
      LalKu89oL8PUBg9J9mMaQTAfBgNVHSMEGDAWgBQXa9VPLalKu89oL8PUBg9J9mMa
      QTANBgkqhkiG9w0BAQsFAAOCAQEAs46eXJLEiWM7WVii0daJwcY6CjQCT9w76vP+
      V2P3oCRXP+UCTZASIqZRpi64T99R7bM7W7Fda16rpyoy/xcMp0sayrfKkr/j4Nzp
      D6rvx03p38uD5da7M/WblMvjEIZ/aA2D3BjhCde3FPE6q5cpF+X9Rhk2B6MX6Sej
      qCyQ02EDqlTURydLVf63yq4C+166MCtHwKqNRcRT58RUE1svCAFfdBWhU4DKv+WK
      GF0JCAztNK9OhBWcw7iAXYfCHuh7sCfseF51Pm7S54/hMmz9DzGIkAF+4Rq9GT2c
      DuGA0xePSTcjY3jrojdZJovgoxXAcjfwCC7pBYuqu1PrTK5GTw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      release.openshift.io/create-only: "true"
      service.beta.openshift.io/inject-cabundle: "true"
    creationTimestamp: "2025-11-17T09:05:35Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:release.openshift.io/create-only: {}
            f:service.beta.openshift.io/inject-cabundle: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:35Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:service-ca.crt: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:34Z"
    name: etcd-service-ca-bundle
    namespace: openshift-etcd-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "7577"
    uid: 4dc6aa41-5878-4e9c-9156-70afd734ec69
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDMjCCAhqgAwIBAgIIHHgNzc5//4QwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
      CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
      HhcNMjUxMTE3MDgyMzQ0WhcNMzUxMTE1MDgyMzQ0WjA3MRIwEAYDVQQLEwlvcGVu
      c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBANwah5f1ohm8Juc7YZqAadlQY1CJYN3F
      j13m9boZMGdqqpZk2rK5UW+RNnU7oLAZ6y7vncfZNPjPa58prLOAb+JPs0Pz2RRQ
      LuJivgwMLLKM0/n6pyXXWfGw35Orv4ZwFhw1R6PxndtKRItLuf6WuI4BZQt55OaR
      frOMCiEyloteSVM1qQdiSloC83kcMr6rmEkG0CGmZynelhq823tNAJiRu9lTy1DP
      e7Xn9DeysUjaQG4n2C+Ftx8rIqacm4ZpSE0/HyiM+pWUZQVHO4mjQCx/XaWC1n7n
      YdLbGzcyjZCVBEJ0uzyx23enGtFrtE7/OzLhx0b8D04fXCrGWk5ObyMCAwEAAaNC
      MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJUN
      /eaUADzHMB3uTyJGFINOBL0YMA0GCSqGSIb3DQEBCwUAA4IBAQCC/k7GoEY6p795
      uMnIPcx3e83IoNBJR+eBOluNVsaf6mPJ4PD6z8MUfHpEskvG1rFljc7MFwimoNRL
      TmYXMlcwxRKcK/9gevs7GcVZWHlbTQEA3/J2AdoWDBYRSgIs/lmRtH0LChPLE1Df
      OuZa+oiroeZUDa3k3jMTIv7ikD15F/CrjIRH91K1QUwr1f/McITQm85ycxqkezcy
      xZSybdqRAlM28X8MJHO9o+CPHdeey/5wtLzX/F51buLbttsOzkOf5xZDXrUA0004
      BwfgHpMm6n6pJxL4KW7FxtI7d7M3r6baPV78hATIMsI72XAnbPVzsz6axuN+VeH5
      xW5zX5aD
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDQDCCAiigAwIBAgIIBJsSoG5kz70wDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
      CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
      c2lnbmVyMB4XDTI1MTExNzA4MjM0NFoXDTM1MTExNTA4MjM0NFowPjESMBAGA1UE
      CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
      c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwr3ve9Q8XF9Q
      k/Qnv/topXVMpnqk1SvmnRawkDDur76VIsvMQPzeAs0x/LIgNjCsQGZbw1uH4XDc
      1GGBYr33sdksFFEp0medGkdVxAQS/XBSHkIlwyit+HDByEGJTK3RC6U0rd3lU9ke
      ZmdSfSFrFi0njC0wb+OczL3An/+uQ+99H7EreBktjB12n1/joDmRihHIhjPMxYRJ
      p3nteLehHdF1ltXAAcfILiyiptjr4tGjzbWJOvrg48O/raV/ApusiDv6dkWYSOIV
      xKpWvbtSH2t8oGrkfrA0qrkfgHeIbGFFGFFBJRJ2eP8LUjA3igA2f7RgyxuMrIKX
      kg3pnpWk3QIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
      /zAdBgNVHQ4EFgQUgrRTQPDqEN/ntTkRotlW0m/c7DIwDQYJKoZIhvcNAQELBQAD
      ggEBAHffGVowOxIIkKFuaab/q8eTWxgGULImUFx8YmdvRenkRRsn1wiLaeZ4C1gz
      hj+vSBU4tAr0gM45krx7Y8Rv63hHFeWf3NuVY3bgMZ2F9HmdOvsFT0zT9B2pRHZZ
      PY9Tyk1dZSwXDstxEcKFeO6THp3mufHiq/Q93jERrUxv3QS+d4YqW2WBxNgWpfA4
      FL2GMOcdFHCFWi6C3wEXfNld7cKeKeVXODiylNYETHmcXxTJKNgr30iAK721U6MR
      KZsBEoW9pVTLzPIatBFet60EHK3koCUSz8bEbIxSg2Z0lWPnBFrLEti/J8tEPE1G
      1pvzzZFMXGIeDRxrZHCQfdFd1is=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDTDCCAjSgAwIBAgIISPV+UhcVQCwwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
      CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
      dHdvcmstc2lnbmVyMB4XDTI1MTExNzA4MjM0NFoXDTM1MTExNTA4MjM0NFowRDES
      MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
      aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAyQYD92TOQPu8PjzdsB0pfu2h1RdjOkFMzDbVcMOXzeJeNNU3QyDLiXbpF4Um
      MtnaAFKI5+Lixu4D7YuRmrh3L8wo+FBOyi1MvQ+t0jivE4xLxszfpX523VyiGPOy
      CVaTF299NTvdBnPZTexQrqEkLDtVM+fUndpEj7XmyUYXjcsNQNPaMcpYsHPjGtwd
      R0cmvXgYvj8Qp0qIbZoaj9iHpHGnSD+kbZAOdcib0cUwJKyVciyyv6YFdda/HmEm
      vMEIfLAOeISRFN7acyvbsOxU0QQUcVmWsM3YbdshCjJJ6J9AgWRN/uXnqzeQWlJy
      qLMRc/PO/s4qhiWkcftTnGyJUwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
      VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUcbLSzO3WDmOy7afA4EAxVL5R51EwDQYJ
      KoZIhvcNAQELBQADggEBAJLBwpS3sVr5OOEqkqax4DV99SMTCzRHAOyAzTXf025D
      YlbxTrnvBZp4yUuniPttgtGi0Zyth7MLYHrp0nQcIWBRNKmt2b6+fb2AzEdSwQii
      oSII/5yN8XIHjqsPAPifV2K3f8VDVhOV6FrhiNqVY+KgnIFkKVmPMRjQI2Cktvzs
      kPtQ7buIaZiUXTcKPpfzqAJzT+/diqtQngZMa4uuMEcIVXv+ZE0lz+N3w3F6wpS7
      9/cKYPz81zuVFaYqx7xzzKqfUZ0P8/VVDWLH9uDTz4l7S/RYBwWM2xRi4mS+auVc
      0amS4vxqS+TkEuBD4EuPFIYc2Bz7XfrW3rpXLN1wOsQ=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDlzCCAn+gAwIBAgIIEdYGC8Zueq4wDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
      AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
      ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzYzMzcxMjI5MB4XDTI1MTExNzA5MjAy
      OFoXDTM1MTExNTA5MjAyOVowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
      c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
      ckAxNzYzMzcxMjI5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyEwQ
      DYRhEETK5M4/B+3PJhRS9xIOk7+h5DWa8qUESoDAJdaUrqpt5XOUTc3U8fvaKdrY
      VH+f62m3C2vMv6w3gHPyI7smokXzrN0FPdbFr3bXLPvwddWC+jTiDkc45ewcicud
      GGTHp1gS4XVdmPTD4I4xj+UoHOesB9+gLN2nuPoj0Fndhv7MURyyxOh1jgR/WC1T
      5OLoqqZXgyLb3pJQRITOcM2R/e581LC+y7rLR+C1VIrkArrdf/vpgumOisamuS1V
      /aObQRkhZJiZGWUQwBUgYCyekewLvbCyPwWXtw7xSj/XuKw8SKpAmSn1+31jFuLY
      UgduO9NYzFBlcR8FyQIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
      BAUwAwEB/zAdBgNVHQ4EFgQU46Cyxbpz+FO5LRelJXgkGsHGWGowHwYDVR0jBBgw
      FoAU46Cyxbpz+FO5LRelJXgkGsHGWGowDQYJKoZIhvcNAQELBQADggEBAKRlOnNx
      6c6qARRMEz1NZ6JlsG90kmxilofSMMcrxiNwUqohX6aiNh7O+uYAWZX52eMJKklm
      rRY1D4E0km0vsQXfTcMLbUIwycvqfzTMRflZ3s8l+nDnIlpyP7Oi0V/+AfJZTWUF
      FggDXmNENiJHH4dCMk+IgieKyYEAmtVjdribmxprLU99pe8oq4pTI2/0Z+lukH63
      Cau6TigbdKu9/KU3KzWnpYyQKrllHLVGXNFqbv0mZWmPA1w+d5zFCmeHFDxXCGtn
      +iIIEpvSZNEFco7kqLBYVj1hF+Wy8KU60oBX18IEOvYwwoCH/U6Htcrftisfi1NY
      PlMzSu7rjEW4pgQ=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDgzCCAmugAwIBAgIICv1WhQwJKBEwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
      AwwbaW5ncmVzcy1vcGVyYXRvckAxNzYzMzcxMzA5MB4XDTI1MTExNzA5MjE0OFoX
      DTI3MTExNzA5MjE0OVowMTEvMC0GA1UEAwwmKi5hcHBzLmhseGNsNTEubGFiLmVu
      Zy50bHYyLnJlZGhhdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQC3rIa4+opCUMXgb3mEtgts6XISeJ4F373tMI8egGfdlOniX70/0bqaC09X5KHH
      m1+pMZi1xaG7NqOfE8gcs9GlTZAsusy//IlTtjXtpfTG0e07xWspzzmajp4PsvYX
      CBUmGpyubqIrv1zNugDTepqwAZYNBiZ8PgKpzRf+MttMxeG4bniasocLq1hmq8fZ
      HY8jZ3BI5tiakvB2CziUKm28ViddM+yyAxvIJ4ayXhzCc5wYN/Cdxpa09qAndeAu
      QiDPMnLgtZfx9TcXK1ORQyLA9+lU9z1XlZxXI3fggjv1ABU1nyNCKeU4PvVncIpf
      SrPn3vkiESnvRq87LZRBUim9AgMBAAGjgakwgaYwDgYDVR0PAQH/BAQDAgWgMBMG
      A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFNTzfwzK
      d6ikdZ7me+UIMXGpIiWKMB8GA1UdIwQYMBaAFN0G4qQTKqRjGHCGhckfrINChtF3
      MDEGA1UdEQQqMCiCJiouYXBwcy5obHhjbDUxLmxhYi5lbmcudGx2Mi5yZWRoYXQu
      Y29tMA0GCSqGSIb3DQEBCwUAA4IBAQAHduCk357TlUutwzNzesExzrnqI3/aftcP
      yBXNe7hqy4xRX5J3iDngNglB43EDMyBZ95r/bF08VCGz8z+O0HLQacJKoGfuhdE/
      PGaiN6mFeM5PdzNNq08DIKiVVwhLklgK6BP4F/AP+ktAFGE8gVQwbZC8hHESgYPN
      /dQhahXYxtQ0VzQO33LXrlZHX3AgR227FGucqLcn8CXS4UekYXz9bCjs+571TjhW
      gaNqkXYTmCeeMdzUrmbUtHnlrhw4YFSKcsxmGfMtwBkovkzKlF+Y/haw1OXYkgBt
      sdy2gPbW6VQWGDSBhO9CBY/51jACuFnUlWTVO0t4qaJi3fjeSTkS
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
      ZXNzLW9wZXJhdG9yQDE3NjMzNzEzMDkwHhcNMjUxMTE3MDkyMTQ4WhcNMjcxMTE3
      MDkyMTQ5WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3NjMzNzEzMDkw
      ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDcBDMP+nEOv38P0CCHXWsx
      MAGI56RxiRgdlyzVIDeIWfxWJcCVaFZ6/UJvv6dF8EapyKI0huy0Q9tAr8N1klWw
      cFiG4XIdR1dYZSHazWyL6zSM9EI1/zCQOZ4VE2RAW5axchBKOwX90GMqpXRZ3nA2
      TJwAwXzgeKHIlSoS5SmN3/EWYuOjoJNx3bLQ/B0O89wxOF14doWz5YUSmDzoL8A3
      A3yX/m2h1FXxRxrcs4ov1Gcty7aeaUcySzp7E+4Wkvhrg4vmuyEMAdPjDVO9bcBa
      MnJ4BcP4gALMP6EJQziC1CRkJqdQ4+KjZwlYIzbGXz3HJuOBT3S5ZLizF2hBgwdx
      AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
      A1UdDgQWBBTdBuKkEyqkYxhwhoXJH6yDQobRdzANBgkqhkiG9w0BAQsFAAOCAQEA
      N4RmQr545nyCl2NX8THv5Q8TMjtxTi/dUIF07kVpJQN94RFOuL+fZer6FIg160a/
      +8E2gzZwoybRonPN7zMbw4VRg/EiPZPd/wODliCwW1l+C5ivnZTJIHinLf0+U6sk
      RoIVzd2kIhU63ph8/+SJ/RyVDZKfK7n3OTGUg7e1rwt2ZgL7KMSU2SZ00hM/lqlE
      pvv+GzoGMOiKTtN6J197PtSGf9KisSGsCTPGN1a7HEUimUDZGNNWKPRHNLcPXkXh
      ifC1j/koiwqu89nAHOzQb1n5fYVp0DQ8Gey/Nj1ytgqC42J63HFX1FFdVcaEJFdw
      z6TlPivqlTLLMZC8ilU41w==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-11-17T09:05:24Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-11-17T09:27:16Z"
    name: kube-root-ca.crt
    namespace: openshift-etcd-operator
    resourceVersion: "14480"
    uid: 35217763-2e1f-4d84-8f14-38e53c7e9f89
- apiVersion: v1
  data:
    service-ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIIHKUjOpzJvOowDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
      Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc2MzM3MTIyMDAe
      Fw0yNTExMTcwOTIwMTlaFw0yODAxMTYwOTIwMjBaMDYxNDAyBgNVBAMMK29wZW5z
      aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NjMzNzEyMjAwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJZslGqtAyG+AF1bCbVlUs9sQRLkmJ7l6v
      lUzDwf7FOFhJEqdN7VkIx0nX/mxYUYV1jGURo06noKZrWV6z4LXOfcw4X4XIOzkx
      YNm1kyD9MJGyx6Uv9ZxiAsguqqGwBt0Sf8fXbcqSBCcty7Myr0BNsB/K3FJvbE8p
      nTx+1G+PrmBkRES8GJe7Av7S31gnvZl2J6V7EkyIBJtSHt57Zcs9FBmuDQcphPhg
      38jgQhzlLpUbLMkcJLAD9/polbrprn4prszIlJeew5AqkVsBKffJzeikRgtxU97L
      VkmInVytBlB7mp7rjuIl3mB7oimj5UfVwdT5FG+KwDiaoboG41Q9AgMBAAGjYzBh
      MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQXa9VP
      LalKu89oL8PUBg9J9mMaQTAfBgNVHSMEGDAWgBQXa9VPLalKu89oL8PUBg9J9mMa
      QTANBgkqhkiG9w0BAQsFAAOCAQEAs46eXJLEiWM7WVii0daJwcY6CjQCT9w76vP+
      V2P3oCRXP+UCTZASIqZRpi64T99R7bM7W7Fda16rpyoy/xcMp0sayrfKkr/j4Nzp
      D6rvx03p38uD5da7M/WblMvjEIZ/aA2D3BjhCde3FPE6q5cpF+X9Rhk2B6MX6Sej
      qCyQ02EDqlTURydLVf63yq4C+166MCtHwKqNRcRT58RUE1svCAFfdBWhU4DKv+WK
      GF0JCAztNK9OhBWcw7iAXYfCHuh7sCfseF51Pm7S54/hMmz9DzGIkAF+4Rq9GT2c
      DuGA0xePSTcjY3jrojdZJovgoxXAcjfwCC7pBYuqu1PrTK5GTw==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      service.beta.openshift.io/inject-cabundle: "true"
    creationTimestamp: "2025-11-17T09:05:24Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:annotations:
            .: {}
            f:service.beta.openshift.io/inject-cabundle: {}
      manager: kube-controller-manager
      operation: Update
      time: "2025-11-17T09:05:24Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:service-ca.crt: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:34Z"
    name: openshift-service-ca.crt
    namespace: openshift-etcd-operator
    resourceVersion: "7584"
    uid: bdb96f43-323f-425b-9417-488a5d0f89b4
kind: ConfigMapList
metadata:
  resourceVersion: "32433"
