---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c25,c10
    openshift.io/sa.scc.supplemental-groups: 1000620000/10000
    openshift.io/sa.scc.uid-range: 1000620000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2025-11-17T09:21:49Z"
  labels:
    kubernetes.io/metadata.name: openshift-ingress
    name: openshift-ingress
    network.openshift.io/policy-group: ingress
    olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: ""
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    policy-group.network.openshift.io/ingress: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:name: {}
          f:network.openshift.io/policy-group: {}
          f:openshift.io/cluster-monitoring: {}
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/enforce: {}
          f:pod-security.kubernetes.io/warn: {}
          f:policy-group.network.openshift.io/ingress: {}
    manager: Go-http-client
    operation: Update
    time: "2025-11-17T09:21:49Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2025-11-17T09:21:49Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: {}
    manager: olm
    operation: Update
    time: "2025-11-17T09:27:09Z"
  name: openshift-ingress
  resourceVersion: "14092"
  uid: fefac46c-11ae-4eee-ad1d-991b05f004a0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
