---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/description: OpenShift cloud network config controller namespace
      - a controller used to manage cloud-level network configuration
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c13,c7
    openshift.io/sa.scc.supplemental-groups: 1000170000/10000
    openshift.io/sa.scc.uid-range: 1000170000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2025-11-17T09:05:23Z"
  labels:
    kubernetes.io/metadata.name: openshift-cloud-network-config-controller
    olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: ""
    openshift.io/cluster-monitoring: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2025-11-17T09:05:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/description: {}
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/cluster-monitoring: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:05:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: {}
    manager: olm
    operation: Update
    time: "2025-11-17T09:21:36Z"
  name: openshift-cloud-network-config-controller
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "9150"
  uid: f4e387de-b5fe-4c8c-8fbb-f7fd6c0dfb64
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
