---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-11-17T09:05:39Z"
  generation: 1
  managedFields:
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      f:spec:
        .: {}
        f:providerSpec:
          .: {}
          f:apiVersion: {}
          f:kind: {}
        f:secretRef:
          .: {}
          f:name: {}
          f:namespace: {}
        f:serviceAccountNames: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:05:39Z"
  - apiVersion: cloudcredential.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:lastSyncGeneration: {}
        f:provisioned: {}
    manager: Go-http-client
    operation: Update
    subresource: status
    time: "2025-11-17T09:06:02Z"
  name: openshift-cloud-network-config-controller-openstack
  namespace: openshift-cloud-credential-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "2270"
  uid: 6a42ab2d-9231-4d0c-b1c1-ec735b4f00e8
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
  secretRef:
    name: cloud-credentials
    namespace: openshift-cloud-network-config-controller
  serviceAccountNames:
  - cloud-network-config-controller
status:
  conditions:
  - lastProbeTime: "2025-11-17T09:06:02Z"
    lastTransitionTime: "2025-11-17T09:06:02Z"
    message: CredentialsRequest is not for platform BareMetal
    reason: InfrastructureMismatch
    status: "True"
    type: Ignored
  lastSyncGeneration: 0
  provisioned: false
