---
apiVersion: v1
data:
  consoleURL: https://console-openshift-console.apps.hlxcl51.XXXXXXXXXXXXXXXXXXXXXXX
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-17T09:38:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:consoleURL: {}
    manager: console
    operation: Update
    time: "2025-11-17T09:38:37Z"
  name: console-public
  namespace: openshift-config-managed
  resourceVersion: "24126"
  uid: 6eecf1bb-ae73-4d48-86c1-9309b16f2641
