---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-11-17T09:05:27Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:05:27Z"
  name: v1.ingress.operator.openshift.io
  resourceVersion: "949"
  uid: 3359cbf0-61e8-4fd7-b8be-7f8f1028272f
spec:
  group: ingress.operator.openshift.io
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-11-17T09:05:27Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
