---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-11-17T09:05:39Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:05:39Z"
  name: v1.machineconfiguration.openshift.io
  resourceVersion: "1471"
  uid: 3b626f43-297c-4c1c-87a4-bc499b485f4c
spec:
  group: machineconfiguration.openshift.io
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-11-17T09:05:39Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
