---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:04:40Z"
    labels:
      component: apiserver
      provider: kubernetes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:component: {}
            f:provider: {}
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kube-apiserver
      operation: Update
      time: "2025-11-17T09:04:40Z"
    name: kubernetes
    namespace: default
    resourceVersion: "239"
    uid: ea593adc-7a8d-4de6-a175-d691d0b07572
  spec:
    clusterIP: 172.30.0.1
    clusterIPs:
    - 172.30.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:21:44Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:externalName: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: Go-http-client
      operation: Update
      time: "2025-11-17T09:21:44Z"
    name: openshift
    namespace: default
    resourceVersion: "9632"
    uid: 6769ce51-8702-41bc-a07e-81e634a1a460
  spec:
    externalName: kubernetes.default.svc.cluster.local
    sessionAffinity: None
    type: ExternalName
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "32330"
