---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c22,c4
    openshift.io/sa.scc.supplemental-groups: 1000470000/10000
    openshift.io/sa.scc.uid-range: 1000470000/10000
  creationTimestamp: "2025-11-17T09:05:47Z"
  labels:
    kubernetes.io/metadata.name: openshift-config
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2025-11-17T09:05:47Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/node-selector: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/run-level: {}
          f:pod-security.kubernetes.io/audit: {}
          f:pod-security.kubernetes.io/enforce: {}
          f:pod-security.kubernetes.io/warn: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:05:47Z"
  name: openshift-config
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "1727"
  uid: 39102ff4-76c6-493c-b85a-5978c99e6902
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
