---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:32:51Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:32:51Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:51:44Z"
  name: buildconfigs.v1.build.openshift.io
  resourceVersion: "32374"
  uid: e4c0ca1c-1137-4a88-8d5e-3c7c66b79626
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      nodeName: XXXXXXXXXXX
      requestCount: 2
    - byUser:
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: openshift-state-metrics/UNKNOWN
        username: system:serviceaccount:openshift-monitoring:openshift-state-metrics
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 13
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-state-metrics/UNKNOWN
        username: system:serviceaccount:openshift-monitoring:openshift-state-metrics
      nodeName: XXXXXXXXXXX
      requestCount: 8
    requestCount: 23
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      nodeName: XXXXXXXXXXX
      requestCount: 2
    - byUser:
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: openshift-state-metrics/UNKNOWN
        username: system:serviceaccount:openshift-monitoring:openshift-state-metrics
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 13
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: openshift-controller-manager/v0.0.0
        username: system:serviceaccount:openshift-controller-manager:openshift-controller-manager-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-state-metrics/UNKNOWN
        username: system:serviceaccount:openshift-monitoring:openshift-state-metrics
      nodeName: XXXXXXXXXXX
      requestCount: 8
    requestCount: 23
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 23
