---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:43:45Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:43:45Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:47:12Z"
  name: costmanagementmetricsconfigs.v1beta1.costmanagement-metrics-cfg.openshift.io
  resourceVersion: "30493"
  uid: 55752d2f-72fe-4f6c-8d92-0bc2ff5e81cd
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 1
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 1
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 1
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 1
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 1
