---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:13:20Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:13:20Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:51:09Z"
  name: mutatingwebhookconfigurations.v1.admissionregistration.k8s.io
  resourceVersion: "32042"
  uid: 9ecfd746-28a3-46b9-b44e-61860e9cbb12
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 4
          verb: watch
        requestCount: 6
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: kube-state-metrics/v2.9.2
        username: system:serviceaccount:openshift-monitoring:kube-state-metrics
      nodeName: XXXXXXXXXXX
      requestCount: 17
    - byUser:
      - byVerb:
        - requestCount: 20
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 23
        userAgent: machine-api-operator/v0.0.0
        username: system:serviceaccount:openshift-machine-api:machine-api-operator
      - byVerb:
        - requestCount: 19
          verb: list
        requestCount: 19
        userAgent: olm/v0.0.0
        username: system:serviceaccount:openshift-operator-lifecycle-manager:olm-operator-serviceaccount
      - byVerb:
        - requestCount: 4
          verb: list
        - requestCount: 6
          verb: watch
        requestCount: 10
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      - byVerb:
        - requestCount: 3
          verb: list
        - requestCount: 5
          verb: watch
        requestCount: 8
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 4
          verb: watch
        requestCount: 6
        userAgent: service-ca-operator/v0.0.0
        username: system:serviceaccount:openshift-service-ca:service-ca
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 78
    - byUser:
      - byVerb:
        - requestCount: 4
          verb: list
        requestCount: 4
        userAgent: olm/v0.0.0
        username: system:serviceaccount:openshift-operator-lifecycle-manager:olm-operator-serviceaccount
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: service-ca-operator/v0.0.0
        username: system:serviceaccount:openshift-service-ca:service-ca
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      nodeName: XXXXXXXXXXX
      requestCount: 10
    requestCount: 105
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 4
          verb: watch
        requestCount: 6
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: kube-state-metrics/v2.9.2
        username: system:serviceaccount:openshift-monitoring:kube-state-metrics
      nodeName: XXXXXXXXXXX
      requestCount: 17
    - byUser:
      - byVerb:
        - requestCount: 20
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 23
        userAgent: machine-api-operator/v0.0.0
        username: system:serviceaccount:openshift-machine-api:machine-api-operator
      - byVerb:
        - requestCount: 19
          verb: list
        requestCount: 19
        userAgent: olm/v0.0.0
        username: system:serviceaccount:openshift-operator-lifecycle-manager:olm-operator-serviceaccount
      - byVerb:
        - requestCount: 4
          verb: list
        - requestCount: 6
          verb: watch
        requestCount: 10
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      - byVerb:
        - requestCount: 3
          verb: list
        - requestCount: 5
          verb: watch
        requestCount: 8
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 4
          verb: watch
        requestCount: 6
        userAgent: service-ca-operator/v0.0.0
        username: system:serviceaccount:openshift-service-ca:service-ca
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 78
    - byUser:
      - byVerb:
        - requestCount: 4
          verb: list
        requestCount: 4
        userAgent: olm/v0.0.0
        username: system:serviceaccount:openshift-operator-lifecycle-manager:olm-operator-serviceaccount
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: kube-apiserver/v1.27.16+03a907c
        username: system:apiserver
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: service-ca-operator/v0.0.0
        username: system:serviceaccount:openshift-service-ca:service-ca
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: oauth-apiserver/v0.0.0
        username: system:serviceaccount:openshift-oauth-apiserver:oauth-apiserver-sa
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: openshift-apiserver/v0.0.0
        username: system:serviceaccount:openshift-apiserver:openshift-apiserver-sa
      nodeName: XXXXXXXXXXX
      requestCount: 10
    requestCount: 105
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 105
