---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:10:16Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:10:16Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:50:02Z"
  name: networks.v1.config.openshift.io
  resourceVersion: "31508"
  uid: 4c9314ba-197c-4b58-8129-34dfe6d6f060
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 7
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 9
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-cloud-controller-manager-operator:cluster-cloud-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver:localhost-recovery-client
      - byVerb:
        - requestCount: 1
          verb: get
        - requestCount: 1
          verb: patch
        requestCount: 2
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 1
          verb: create
        - requestCount: 1
          verb: get
        requestCount: 2
        userAgent: cluster-bootstrap/v0.0.0
        username: system:admin
      nodeName: XXXXXXXXXXX
      requestCount: 21
    - byUser:
      - byVerb:
        - requestCount: 24
          verb: get
        requestCount: 24
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-ingress-operator:ingress-operator
      - byVerb:
        - requestCount: 19
          verb: get
        requestCount: 19
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-dns-operator:dns-operator
      - byVerb:
        - requestCount: 12
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 14
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-openshift-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-controller-manager-operator:openshift-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: machine-config-operator/v0.0.0
        username: system:serviceaccount:openshift-machine-config-operator:machine-config-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-kube-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-controller-manager-operator:kube-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-etcd-operator/v0.0.0
        username: system:serviceaccount:openshift-etcd-operator:etcd-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 1
          verb: get
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 76
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-kube-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-controller-manager-operator:kube-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 6
    requestCount: 103
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 7
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 9
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-cloud-controller-manager-operator:cluster-cloud-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver:localhost-recovery-client
      - byVerb:
        - requestCount: 1
          verb: get
        - requestCount: 1
          verb: patch
        requestCount: 2
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 1
          verb: create
        - requestCount: 1
          verb: get
        requestCount: 2
        userAgent: cluster-bootstrap/v0.0.0
        username: system:admin
      nodeName: XXXXXXXXXXX
      requestCount: 21
    - byUser:
      - byVerb:
        - requestCount: 24
          verb: get
        requestCount: 24
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-ingress-operator:ingress-operator
      - byVerb:
        - requestCount: 19
          verb: get
        requestCount: 19
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-dns-operator:dns-operator
      - byVerb:
        - requestCount: 12
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 14
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-openshift-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-controller-manager-operator:openshift-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: machine-config-operator/v0.0.0
        username: system:serviceaccount:openshift-machine-config-operator:machine-config-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-kube-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-controller-manager-operator:kube-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-etcd-operator/v0.0.0
        username: system:serviceaccount:openshift-etcd-operator:etcd-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 2
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 1
          verb: get
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 76
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-kube-controller-manager-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-controller-manager-operator:kube-controller-manager-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 6
    requestCount: 103
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 103
