---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:13:17Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:13:17Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:50:37Z"
  name: prometheuses.v1.monitoring.coreos.com
  resourceVersion: "31792"
  uid: bfe5f841-ccc7-460c-94e9-dcd0ff6b9df9
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: cluster-policy-controller/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: get
        requestCount: 1
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      nodeName: XXXXXXXXXXX
      requestCount: 12
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: create
        - requestCount: 5
          verb: delete
        - requestCount: 17
          verb: get
        - requestCount: 5
          verb: list
        - requestCount: 4
          verb: update
        requestCount: 32
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 29
          verb: update
        - requestCount: 1
          verb: watch
        requestCount: 31
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 2
          verb: get
        requestCount: 2
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 74
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 3
    requestCount: 89
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: cluster-policy-controller/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: get
        requestCount: 1
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      nodeName: XXXXXXXXXXX
      requestCount: 12
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: create
        - requestCount: 5
          verb: delete
        - requestCount: 17
          verb: get
        - requestCount: 5
          verb: list
        - requestCount: 4
          verb: update
        requestCount: 32
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 29
          verb: update
        - requestCount: 1
          verb: watch
        requestCount: 31
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 5
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 2
          verb: get
        requestCount: 2
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 1
          verb: list
        requestCount: 1
        userAgent: insights-operator/v0.0.0
        username: system:serviceaccount:openshift-insights:gather
      nodeName: XXXXXXXXXXX
      requestCount: 74
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 3
    requestCount: 89
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 89
