---
apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  creationTimestamp: "2025-11-17T09:12:47Z"
  generation: 1
  managedFields:
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:numberOfUsersToReport: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-11-17T09:12:47Z"
  - apiVersion: apiserver.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:currentHour:
          .: {}
          f:byNode: {}
          f:requestCount: {}
        f:last24h: {}
        f:requestCount: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-11-17T09:51:19Z"
  name: prometheusrules.v1.monitoring.coreos.com
  resourceVersion: "32133"
  uid: 3be234bf-6a1d-4f15-b11b-bb99da749883
spec:
  numberOfUsersToReport: 10
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 16
          verb: create
        - requestCount: 152
          verb: get
        requestCount: 168
        userAgent: cluster-version-operator/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 12
          verb: delete
        - requestCount: 76
          verb: get
        - requestCount: 1
          verb: watch
        requestCount: 89
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 75
          verb: get
        requestCount: 75
        userAgent: cluster-version-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-version:default
      - byVerb:
        - requestCount: 3
          verb: delete
        - requestCount: 31
          verb: get
        - requestCount: 31
          verb: update
        - requestCount: 1
          verb: watch
        requestCount: 66
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 20
          verb: get
        - requestCount: 20
          verb: patch
        requestCount: 40
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 22
          verb: get
        requestCount: 22
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 2
          verb: watch
        requestCount: 2
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-storage-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-storage-operator:cluster-storage-operator
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-machine-api:cluster-autoscaler-operator
      nodeName: XXXXXXXXXXX
      requestCount: 472
    - byUser:
      - byVerb:
        - requestCount: 42
          verb: delete
        - requestCount: 266
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 310
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 10
          verb: create
        - requestCount: 3
          verb: delete
        - requestCount: 26
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 16
          verb: update
        - requestCount: 2
          verb: watch
        requestCount: 58
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 26
          verb: get
        - requestCount: 26
          verb: patch
        requestCount: 52
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 43
          verb: get
        requestCount: 43
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-storage-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-storage-operator:cluster-storage-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-machine-api:cluster-autoscaler-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 480
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 3
    requestCount: 955
  last24h:
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - byUser:
      - byVerb:
        - requestCount: 16
          verb: create
        - requestCount: 152
          verb: get
        requestCount: 168
        userAgent: cluster-version-operator/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 12
          verb: delete
        - requestCount: 76
          verb: get
        - requestCount: 1
          verb: watch
        requestCount: 89
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 75
          verb: get
        requestCount: 75
        userAgent: cluster-version-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-version:default
      - byVerb:
        - requestCount: 3
          verb: delete
        - requestCount: 31
          verb: get
        - requestCount: 31
          verb: update
        - requestCount: 1
          verb: watch
        requestCount: 66
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 20
          verb: get
        - requestCount: 20
          verb: patch
        requestCount: 40
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 22
          verb: get
        requestCount: 22
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 3
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:admin
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:admin
      - byVerb:
        - requestCount: 2
          verb: watch
        requestCount: 2
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: cluster-storage-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-storage-operator:cluster-storage-operator
      - byVerb:
        - requestCount: 1
          verb: watch
        requestCount: 1
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-machine-api:cluster-autoscaler-operator
      nodeName: XXXXXXXXXXX
      requestCount: 472
    - byUser:
      - byVerb:
        - requestCount: 42
          verb: delete
        - requestCount: 266
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 1
          verb: watch
        requestCount: 310
        userAgent: cluster-kube-apiserver-operator/v0.0.0
        username: system:serviceaccount:openshift-kube-apiserver-operator:kube-apiserver-operator
      - byVerb:
        - requestCount: 10
          verb: create
        - requestCount: 3
          verb: delete
        - requestCount: 26
          verb: get
        - requestCount: 1
          verb: list
        - requestCount: 16
          verb: update
        - requestCount: 2
          verb: watch
        requestCount: 58
        userAgent: operator/v0.0.0
        username: system:serviceaccount:openshift-monitoring:cluster-monitoring-operator
      - byVerb:
        - requestCount: 26
          verb: get
        - requestCount: 26
          verb: patch
        requestCount: 52
        userAgent: cluster-network-operator/v0.0.0
        username: system:serviceaccount:openshift-network-operator:default
      - byVerb:
        - requestCount: 43
          verb: get
        requestCount: 43
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:serviceaccount:kube-system:generic-garbage-collector
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: PrometheusOperator/0.67.1
        username: system:serviceaccount:openshift-monitoring:prometheus-operator
      - byVerb:
        - requestCount: 2
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 4
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-storage-operator/v0.0.0
        username: system:serviceaccount:openshift-cluster-storage-operator:cluster-storage-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: Go-http-client/2.0
        username: system:serviceaccount:openshift-machine-api:cluster-autoscaler-operator
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: cluster-policy-controller/v0.0.0
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 480
    - byUser:
      - byVerb:
        - requestCount: 1
          verb: list
        - requestCount: 2
          verb: watch
        requestCount: 3
        userAgent: kube-controller-manager/v1.27.16+03a907c
        username: system:kube-controller-manager
      nodeName: XXXXXXXXXXX
      requestCount: 3
    requestCount: 955
  - requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  - byNode:
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    - nodeName: XXXXXXXXXXX
      requestCount: 0
    requestCount: 0
  requestCount: 955
