---
apiVersion: v1
data:
  additional-cert-acceptance-cond.json: |
    [{
      "commonNamePrefix":"system:multus",
      "organizations": ["system:multus"],
      "groups": ["system:nodes", "system:multus", "system:authenticated"],
      "userPrefixes": ["system:node", "system:multus"]
    }]
  additional-pod-admission-cond.json: |
    [{
      "commonNamePrefix":"system:multus",
      "allowedPodAnnotations": ["k8s.v1.cni.cncf.io/network-status"]
    }]
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: |
      This configmap contains the ovnkube-identity configuration files.
  creationTimestamp: "2025-11-17T09:18:40Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:additional-cert-acceptance-cond.json: {}
        f:additional-pod-admission-cond.json: {}
      f:metadata:
        f:annotations:
          f:kubernetes.io/description: {}
        f:ownerReferences:
          k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2025-11-17T09:18:40Z"
  name: ovnkube-identity-cm
  namespace: openshift-network-node-identity
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: de0dec5f-c369-4191-91db-e20c2450d94e
  resourceVersion: "5126"
  uid: cd54df7c-ccb2-4f62-b61c-fa3d19ea1e71
