---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    capability.openshift.io/name: Storage
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2025-11-17T09:20:43Z"
  generation: 1
  labels:
    role: alert-rules
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:capability.openshift.io/name: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
        f:labels:
          .: {}
          f:role: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
      f:spec:
        .: {}
        f:groups:
          .: {}
          k:{"name":"default-storage-classes.rules"}:
            .: {}
            f:name: {}
            f:rules: {}
          k:{"name":"storage-operations.rules"}:
            .: {}
            f:name: {}
            f:rules: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:20:43Z"
  name: prometheus
  namespace: openshift-cluster-storage-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "8053"
  uid: f995f5e5-4346-4075-ac94-9b5752a8ee69
spec:
  groups:
  - name: default-storage-classes.rules
    rules:
    - alert: MultipleDefaultStorageClasses
      annotations:
        description: |
          Cluster storage operator monitors all storage classes configured in the cluster
          and checks there is not more than one default StorageClass configured.
        message: StorageClass count check is failing (there should not be more than
          one default StorageClass)
        summary: More than one default StorageClass detected.
      expr: max_over_time(default_storage_class_count[5m]) > 1
      for: 10m
      labels:
        severity: warning
  - name: storage-operations.rules
    rules:
    - alert: PodStartupStorageOperationsFailing
      annotations:
        description: |
          Failing storage operation "{{ $labels.operation_name }}" of volume plugin {{ $labels.volume_plugin }} was preventing Pods on node {{ $labels.node }}
          from starting for past 5 minutes.
          Please investigate Pods that are "ContainerCreating" on the node: "oc get pod --field-selector=spec.nodeName={{ $labels.node }} --all-namespaces | grep ContainerCreating".
          Events of the Pods should contain exact error message: "oc describe pod -n <pod namespace> <pod name>".
        summary: Pods can't start because {{ $labels.operation_name }} of volume plugin
          {{ $labels.volume_plugin }} is permanently failing on node {{ $labels.node
          }}.
      expr: |
        increase(storage_operation_duration_seconds_count{status != "success", operation_name =~"volume_attach|volume_mount"}[5m]) > 0
        and ignoring(status) increase(storage_operation_duration_seconds_count{status = "success", operation_name =~"volume_attach|volume_mount"}[5m]) == 0
      for: 5m
      labels:
        severity: info
