---
apiVersion: v1
data:
  daemon-config.json: |
    {
        "cniVersion": "0.3.1",
        "chrootDir": "/hostroot",
        "logToStderr": true,
        "logLevel": "verbose",
        "binDir": "/var/lib/cni/bin",

        "perNodeCertificate": {
          "enabled": true,
          "bootstrapKubeconfig": "/var/lib/kubelet/kubeconfig",
          "certDir": "/etc/cni/multus/certs",
          "certDuration": "24h"
        },

        "cniConfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "multusAutoconfigDir": "/host/run/multus/cni/net.d",
        "namespaceIsolation": true,
        "globalNamespaces": "default,openshift-multus,openshift-sriov-network-operator",
        "readinessindicatorfile": "/host/run/multus/cni/net.d/10-ovn-kubernetes.conf",
        "daemonSocketDir": "/run/multus/socket",
        "socketDir": "/host/run/multus/socket"
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-17T09:18:05Z"
  labels:
    app: multus
    tier: node
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:daemon-config.json: {}
      f:metadata:
        f:labels:
          f:app: {}
          f:tier: {}
        f:ownerReferences:
          k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2025-11-17T09:18:05Z"
  name: multus-daemon-config
  namespace: openshift-multus
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: de0dec5f-c369-4191-91db-e20c2450d94e
  resourceVersion: "4669"
  uid: 62aa3e69-aec6-44ed-9119-a1cb36d2d52d
