---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      include.release.openshift.io/self-managed-high-availability: "true"
    creationTimestamp: "2025-11-17T09:18:34Z"
    labels:
      app: network-check-source
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:include.release.openshift.io/self-managed-high-availability: {}
          f:labels:
            f:app: {}
          f:ownerReferences:
            k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            k:{"port":17698,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:targetPort: {}
          f:selector: {}
          f:type: {}
      manager: cluster-network-operator/operconfig
      operation: Apply
      time: "2025-11-17T09:18:34Z"
    name: network-check-source
    namespace: openshift-network-diagnostics
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Network
      name: cluster
      uid: de0dec5f-c369-4191-91db-e20c2450d94e
    resourceVersion: "5047"
    uid: f9ed31bd-4723-49c2-a2de-2cf9d9c5dfc7
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: check-endpoints
      port: 17698
      protocol: TCP
      targetPort: 17698
    selector:
      app: network-check-source
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:18:36Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:ownerReferences:
            k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
        f:spec:
          f:ports:
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
      manager: cluster-network-operator/operconfig
      operation: Apply
      time: "2025-11-17T09:18:36Z"
    name: network-check-target
    namespace: openshift-network-diagnostics
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Network
      name: cluster
      uid: de0dec5f-c369-4191-91db-e20c2450d94e
    resourceVersion: "5083"
    uid: 998399b5-ec7a-4a9d-8cd7-a3f12ef5f872
  spec:
    clusterIP: 172.30.83.180
    clusterIPs:
    - 172.30.83.180
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: network-check-target
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "32585"
