---
apiVersion: v1
data:
  ovnkube.conf: |-
    [default]
    mtu="1400"
    cluster-subnets="10.128.0.0/14/23,fd02::/48/64"
    encap-port="6081"
    enable-lflow-cache=true
    lflow-cache-limit-kb=1048576
    enable-udp-aggregation=true

    [kubernetes]
    service-cidrs="172.30.0.0/16,fd03::/112"
    ovn-config-namespace="openshift-ovn-kubernetes"
    apiserver="https://api-int.hlxcl51.XXXXXXXXXXXXXXXXXXXXXXX:6443"
    host-network-namespace="openshift-host-network"
    platform-type="BareMetal"
    healthz-bind-address="0.0.0.0:10256"
    dns-service-namespace="openshift-dns"
    dns-service-name="dns-default"

    [ovnkubernetesfeature]
    enable-egress-ip=true
    enable-egress-firewall=true
    enable-egress-qos=true
    enable-egress-service=true
    egressip-node-healthcheck-port=9107
    enable-multi-network=true

    [gateway]
    mode=shared
    nodeport=true

    [clustermanager]

    [logging]
    libovsdblogfile=/var/log/ovnkube/libovsdb.log
    logfile-maxsize=100
    logfile-maxbackups=5
    logfile-maxage=0
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-17T09:18:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:ovnkube.conf: {}
      f:metadata:
        f:ownerReferences:
          k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2025-11-17T09:18:21Z"
  name: ovnkube-config
  namespace: openshift-ovn-kubernetes
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: de0dec5f-c369-4191-91db-e20c2450d94e
  resourceVersion: "4859"
  uid: 7a0e4aa8-f0c8-42b6-9f9b-20e6de330a81
