---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      capability.openshift.io/name: NodeTuning
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
      service.beta.openshift.io/serving-cert-secret-name: node-tuning-operator-tls
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
    creationTimestamp: "2025-11-17T09:05:33Z"
    labels:
      name: node-tuning-operator
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:service.beta.openshift.io/serving-cert-secret-name: {}
          f:labels:
            .: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":60000,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:33Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:33Z"
    name: node-tuning-operator
    namespace: openshift-cluster-node-tuning-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "7437"
    uid: c6c859c1-3fd0-4170-b142-c10c3a6278e4
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 60000
      protocol: TCP
      targetPort: 60000
    selector:
      name: cluster-node-tuning-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      capability.openshift.io/name: NodeTuning
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
      service.beta.openshift.io/serving-cert-secret-name: performance-addon-operator-webhook-cert
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
    creationTimestamp: "2025-11-17T09:05:48Z"
    labels:
      name: performance-addon-operator-service
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:service.beta.openshift.io/serving-cert-secret-name: {}
          f:labels:
            .: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:48Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:33Z"
    name: performance-addon-operator-service
    namespace: openshift-cluster-node-tuning-operator
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "7490"
    uid: 84946556-0dde-43d9-8ad8-a993737f8562
  spec:
    clusterIP: 172.30.237.124
    clusterIPs:
    - 172.30.237.124
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: "443"
      port: 443
      protocol: TCP
      targetPort: 4343
    selector:
      name: cluster-node-tuning-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "32463"
