---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:21:47Z"
    labels:
      olm.service-spec-hash: 8bf9c66d9
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:olm.service-spec-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"f0dbea39-0262-46b2-8dcd-8b9ce7efcdf1"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":50051,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: catalog
      operation: Update
      time: "2025-11-17T09:21:47Z"
    name: certified-operators
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: CatalogSource
      name: certified-operators
      uid: f0dbea39-0262-46b2-8dcd-8b9ce7efcdf1
    resourceVersion: "9862"
    uid: d7891de0-1d04-46e4-9610-b8de89aa0547
  spec:
    clusterIP: 172.30.204.175
    clusterIPs:
    - 172.30.204.175
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      olm.catalogSource: certified-operators
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:21:46Z"
    labels:
      olm.service-spec-hash: 59c9d9cc8f
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:olm.service-spec-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"f1f22401-c02c-46d6-9320-4f72006304a8"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":50051,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: catalog
      operation: Update
      time: "2025-11-17T09:21:46Z"
    name: community-operators
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: CatalogSource
      name: community-operators
      uid: f1f22401-c02c-46d6-9320-4f72006304a8
    resourceVersion: "9779"
    uid: dcb90e99-056e-4112-a034-fda5c1b04ae9
  spec:
    clusterIP: 172.30.1.62
    clusterIPs:
    - 172.30.1.62
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      olm.catalogSource: community-operators
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      capability.openshift.io/name: marketplace
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      include.release.openshift.io/single-node-developer: "true"
      service.alpha.openshift.io/serving-cert-secret-name: marketplace-operator-metrics
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
    creationTimestamp: "2025-11-17T09:05:37Z"
    labels:
      name: marketplace-operator
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:capability.openshift.io/name: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:include.release.openshift.io/single-node-developer: {}
            f:service.alpha.openshift.io/serving-cert-secret-name: {}
          f:labels:
            .: {}
            f:name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8081,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":8383,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-11-17T09:05:37Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:44Z"
    name: marketplace-operator-metrics
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      controller: true
      kind: ClusterVersion
      name: version
      uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
    resourceVersion: "8093"
    uid: 8b31bc90-c266-40d2-bc48-778d25aae697
  spec:
    clusterIP: 172.30.19.45
    clusterIPs:
    - 172.30.19.45
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
    - name: https-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      name: marketplace-operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:21:46Z"
    labels:
      olm.service-spec-hash: 66bf85c586
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:olm.service-spec-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a2e9bdc4-f5c3-4403-85ab-762d6b54ffe1"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":50051,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: catalog
      operation: Update
      time: "2025-11-17T09:21:46Z"
    name: redhat-marketplace
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: CatalogSource
      name: redhat-marketplace
      uid: a2e9bdc4-f5c3-4403-85ab-762d6b54ffe1
    resourceVersion: "9784"
    uid: 9d9dc711-459a-4627-8b43-5d4763827807
  spec:
    clusterIP: 172.30.184.161
    clusterIPs:
    - 172.30.184.161
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      olm.catalogSource: redhat-marketplace
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-11-17T09:21:46Z"
    labels:
      olm.service-spec-hash: 54c5b9977b
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:olm.service-spec-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"091c14be-2440-470c-8103-d4ed1f15739d"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":50051,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: catalog
      operation: Update
      time: "2025-11-17T09:21:46Z"
    name: redhat-operators
    namespace: openshift-marketplace
    ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: CatalogSource
      name: redhat-operators
      uid: 091c14be-2440-470c-8103-d4ed1f15739d
    resourceVersion: "9831"
    uid: 385acb11-0331-40a2-be17-1e14cca251ba
  spec:
    clusterIP: 172.30.14.185
    clusterIPs:
    - 172.30.14.185
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      olm.catalogSource: redhat-operators
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "32550"
