---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: "2025-11-17T09:38:36Z"
  generation: 2
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: openshift-monitoring
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:service.beta.openshift.io/inject-cabundle: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
      f:webhooks:
        .: {}
        k:{"name":"alertmanagerconfigs.openshift.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector: {}
          f:objectSelector: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: operator
    operation: Update
    time: "2025-11-17T09:38:36Z"
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:webhooks:
        k:{"name":"alertmanagerconfigs.openshift.io"}:
          f:clientConfig:
            f:caBundle: {}
    manager: service-ca-operator
    operation: Update
    time: "2025-11-17T09:38:36Z"
  name: alertmanagerconfigs.openshift.io
  resourceVersion: "24087"
  uid: 7cc891fc-20d8-4373-a59d-010c5adbe300
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJSEtVak9wekp2T293RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk16TTNNVEl5TURBZQpGdzB5TlRFeE1UY3dPVEl3TVRsYUZ3MHlPREF4TVRZd09USXdNakJhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOak16TnpFeU1qQXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREpac2xHcXRBeUcrQUYxYkNiVmxVczlzUVJMa21KN2w2dgpsVXpEd2Y3Rk9GaEpFcWRON1ZrSXgwblgvbXhZVVlWMWpHVVJvMDZub0tacldWNno0TFhPZmN3NFg0WElPemt4CllObTFreUQ5TUpHeXg2VXY5WnhpQXNndXFxR3dCdDBTZjhmWGJjcVNCQ2N0eTdNeXIwQk5zQi9LM0ZKdmJFOHAKblR4KzFHK1BybUJrUkVTOEdKZTdBdjdTMzFnbnZabDJKNlY3RWt5SUJKdFNIdDU3WmNzOUZCbXVEUWNwaFBoZwozOGpnUWh6bExwVWJMTWtjSkxBRDkvcG9sYnJwcm40cHJzeklsSmVldzVBcWtWc0JLZmZKemVpa1JndHhVOTdMClZrbUluVnl0QmxCN21wN3JqdUlsM21CN29pbWo1VWZWd2RUNUZHK0t3RGlhb2JvRzQxUTlBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFYYTlWUApMYWxLdTg5b0w4UFVCZzlKOW1NYVFUQWZCZ05WSFNNRUdEQVdnQlFYYTlWUExhbEt1ODlvTDhQVUJnOUo5bU1hClFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzNDZlWEpMRWlXTTdXVmlpMGRhSndjWTZDalFDVDl3NzZ2UCsKVjJQM29DUlhQK1VDVFpBU0lxWlJwaTY0VDk5UjdiTTdXN0ZkYTE2cnB5b3kveGNNcDBzYXlyZktrci9qNE56cApENnJ2eDAzcDM4dUQ1ZGE3TS9XYmxNdmpFSVovYUEyRDNCamhDZGUzRlBFNnE1Y3BGK1g5UmhrMkI2TVg2U2VqCnFDeVEwMkVEcWxUVVJ5ZExWZjYzeXE0QysxNjZNQ3RId0txTlJjUlQ1OFJVRTFzdkNBRmZkQldoVTRES3YrV0sKR0YwSkNBenROSzlPaEJXY3c3aUFYWWZDSHVoN3NDZnNlRjUxUG03UzU0L2hNbXo5RHpHSWtBRis0UnE5R1QyYwpEdUdBMHhlUFNUY2pZM2pyb2pkWkpvdmdveFhBY2pmd0NDN3BCWXVxdTFQclRLNUdUdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: prometheus-operator-admission-webhook
      namespace: openshift-monitoring
      path: /admission-alertmanagerconfigs/validate
      port: 8443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: alertmanagerconfigs.openshift.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - monitoring.coreos.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertmanagerconfigs
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 5
