---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: "2025-11-17T09:21:49Z"
  generation: 2
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:service.beta.openshift.io/inject-cabundle: {}
      f:webhooks:
        .: {}
        k:{"name":"vprovisioning.kb.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector: {}
          f:objectSelector: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: cluster-baremetal-operator
    operation: Update
    time: "2025-11-17T09:21:49Z"
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:webhooks:
        k:{"name":"vprovisioning.kb.io"}:
          f:clientConfig:
            f:caBundle: {}
    manager: service-ca-operator
    operation: Update
    time: "2025-11-17T09:21:49Z"
  name: cluster-baremetal-validating-webhook-configuration
  resourceVersion: "10149"
  uid: 52b48b1e-d146-4650-8ee5-8ef32ab57521
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJSEtVak9wekp2T293RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMk16TTNNVEl5TURBZQpGdzB5TlRFeE1UY3dPVEl3TVRsYUZ3MHlPREF4TVRZd09USXdNakJhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOak16TnpFeU1qQXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREpac2xHcXRBeUcrQUYxYkNiVmxVczlzUVJMa21KN2w2dgpsVXpEd2Y3Rk9GaEpFcWRON1ZrSXgwblgvbXhZVVlWMWpHVVJvMDZub0tacldWNno0TFhPZmN3NFg0WElPemt4CllObTFreUQ5TUpHeXg2VXY5WnhpQXNndXFxR3dCdDBTZjhmWGJjcVNCQ2N0eTdNeXIwQk5zQi9LM0ZKdmJFOHAKblR4KzFHK1BybUJrUkVTOEdKZTdBdjdTMzFnbnZabDJKNlY3RWt5SUJKdFNIdDU3WmNzOUZCbXVEUWNwaFBoZwozOGpnUWh6bExwVWJMTWtjSkxBRDkvcG9sYnJwcm40cHJzeklsSmVldzVBcWtWc0JLZmZKemVpa1JndHhVOTdMClZrbUluVnl0QmxCN21wN3JqdUlsM21CN29pbWo1VWZWd2RUNUZHK0t3RGlhb2JvRzQxUTlBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFYYTlWUApMYWxLdTg5b0w4UFVCZzlKOW1NYVFUQWZCZ05WSFNNRUdEQVdnQlFYYTlWUExhbEt1ODlvTDhQVUJnOUo5bU1hClFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzNDZlWEpMRWlXTTdXVmlpMGRhSndjWTZDalFDVDl3NzZ2UCsKVjJQM29DUlhQK1VDVFpBU0lxWlJwaTY0VDk5UjdiTTdXN0ZkYTE2cnB5b3kveGNNcDBzYXlyZktrci9qNE56cApENnJ2eDAzcDM4dUQ1ZGE3TS9XYmxNdmpFSVovYUEyRDNCamhDZGUzRlBFNnE1Y3BGK1g5UmhrMkI2TVg2U2VqCnFDeVEwMkVEcWxUVVJ5ZExWZjYzeXE0QysxNjZNQ3RId0txTlJjUlQ1OFJVRTFzdkNBRmZkQldoVTRES3YrV0sKR0YwSkNBenROSzlPaEJXY3c3aUFYWWZDSHVoN3NDZnNlRjUxUG03UzU0L2hNbXo5RHpHSWtBRis0UnE5R1QyYwpEdUdBMHhlUFNUY2pZM2pyb2pkWkpvdmdveFhBY2pmd0NDN3BCWXVxdTFQclRLNUdUdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: cluster-baremetal-webhook-service
      namespace: openshift-machine-api
      path: /validate-metal3-io-v1alpha1-provisioning
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: vprovisioning.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - provisionings
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
