---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c12,c9
    openshift.io/sa.scc.supplemental-groups: 1000150000/10000
    openshift.io/sa.scc.uid-range: 1000150000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2025-11-17T09:05:22Z"
  labels:
    kubernetes.io/metadata.name: openshift-config-operator
    olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: ""
    openshift.io/cluster-monitoring: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:include.release.openshift.io/single-node-developer: {}
          f:openshift.io/node-selector: {}
          f:workload.openshift.io/allowed: {}
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
          f:openshift.io/cluster-monitoring: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"5b5cce96-2701-4c85-af4f-4dbf8e0e7775"}: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-11-17T09:05:22Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2025-11-17T09:05:23Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:olm.operatorgroup.uid/b2637a98-e91c-4934-979a-9b4b19b95496: {}
    manager: olm
    operation: Update
    time: "2025-11-17T09:21:36Z"
  name: openshift-config-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 5b5cce96-2701-4c85-af4f-4dbf8e0e7775
  resourceVersion: "9164"
  uid: 1be8b06e-e867-436c-a447-473a27975ca3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
