---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: "2025-11-17T09:18:41Z"
  generation: 1
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
      f:spec:
        f:groups:
          k:{"name":"openshift-network.rules"}:
            .: {}
            f:name: {}
            f:rules: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2025-11-17T09:18:41Z"
  name: openshift-network-operator-ipsec-rules
  namespace: openshift-network-operator
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: de0dec5f-c369-4191-91db-e20c2450d94e
  resourceVersion: "5154"
  uid: dcfc9b25-8be7-469b-979a-cb1a991e134e
spec:
  groups:
  - name: openshift-network.rules
    rules:
    - expr: |-
        group by (mode,is_legacy_api) (
          openshift_network_operator_ipsec_state{namespace=~"openshift-network-operator"}
        )
      record: openshift:openshift_network_operator_ipsec_state:info
