---
apiVersion: v1
data:
  applied: '{"managementState":"Managed","logLevel":"Normal","operatorLogLevel":"Normal","unsupportedConfigOverrides":null,"observedConfig":null,"clusterNetwork":[{"cidr":XXXXXXXXXXXXXXX,"hostPrefix":23},{"cidr":"fd02::/48","hostPrefix":64}],"serviceNetwork":[XXXXXXXXXXXXXXX,"fd03::/112"],"defaultNetwork":{"type":"OVNKubernetes","ovnKubernetesConfig":{"mtu":1400,"genevePort":6081,"policyAuditConfig":{"rateLimit":20,"maxFileSize":50,"maxLogFiles":5,"destination":"null","syslogFacility":"local0"},"gatewayConfig":{"ipv4":{},"ipv6":{}},"egressIPConfig":{}}},"disableMultiNetwork":false,"useMultiNetworkPolicy":false,"deployKubeProxy":false,"disableNetworkDiagnostics":false}'
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-17T09:17:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:applied: {}
      f:metadata:
        f:ownerReferences:
          k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2025-11-17T09:18:52Z"
  name: applied-cluster
  namespace: openshift-network-operator
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: de0dec5f-c369-4191-91db-e20c2450d94e
  resourceVersion: "5203"
  uid: ebf36649-6eee-4fb0-a958-e2b4677cb4c4
