---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
      service.beta.openshift.io/serving-cert-secret-name: ovn-control-plane-metrics-cert
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
    creationTimestamp: "2025-11-17T09:18:27Z"
    labels:
      app: ovnkube-control-plane
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.beta.openshift.io/serving-cert-secret-name: {}
          f:labels:
            f:app: {}
          f:ownerReferences:
            k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            k:{"port":9108,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:publishNotReadyAddresses: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-network-operator/operconfig
      operation: Apply
      time: "2025-11-17T09:18:27Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:47Z"
    name: ovn-kubernetes-control-plane
    namespace: openshift-ovn-kubernetes
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Network
      name: cluster
      uid: de0dec5f-c369-4191-91db-e20c2450d94e
    resourceVersion: "8173"
    uid: 24b826d7-01ad-4520-8996-f25962c5c16e
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 9108
      protocol: TCP
      targetPort: 9108
    publishNotReadyAddresses: true
    selector:
      app: ovnkube-control-plane
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
      service.beta.openshift.io/serving-cert-secret-name: ovn-node-metrics-cert
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1763371220
    creationTimestamp: "2025-11-17T09:18:28Z"
    labels:
      app: ovnkube-node
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.beta.openshift.io/serving-cert-secret-name: {}
          f:labels:
            f:app: {}
          f:ownerReferences:
            k:{"uid":"de0dec5f-c369-4191-91db-e20c2450d94e"}: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            k:{"port":9103,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":9105,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:publishNotReadyAddresses: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: cluster-network-operator/operconfig
      operation: Apply
      time: "2025-11-17T09:18:28Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:service.alpha.openshift.io/serving-cert-signed-by: {}
            f:service.beta.openshift.io/serving-cert-signed-by: {}
      manager: service-ca-operator
      operation: Update
      time: "2025-11-17T09:20:48Z"
    name: ovn-kubernetes-node
    namespace: openshift-ovn-kubernetes
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Network
      name: cluster
      uid: de0dec5f-c369-4191-91db-e20c2450d94e
    resourceVersion: "8221"
    uid: cfca4d05-1812-495f-9b92-ea3bd6bb3ccc
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 9103
      protocol: TCP
      targetPort: 9103
    - name: ovn-metrics
      port: 9105
      protocol: TCP
      targetPort: 9105
    publishNotReadyAddresses: true
    selector:
      app: ovnkube-node
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "32575"
